# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Cat_color'),
        ),
    ]
